name: Nic Wong
markdown: kramdown

title: Not Even Wong
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 
  I'm a physicist, musician, and educator by training, and I enjoy seeing numbers jump through hoops.
  <br><br>
  I'll be updating my personal research projects here as time goes by. 
  <br><br>
  <li><a href="/">Home</a></li>
  <li><a href="/cv">CV</a></li>
  <li><a href="mailto:nicwwk@gmail.com">email</a></li>
  <br><br>
  Posts and projects:
	<ul>
	{% for post in site.posts %}
	    <li><span>{{ post.date | date_to_string }}</span> » <a href="{{ post.url }}" title="{{ post.title }}">{{ post.title }}</a></li>
	{% endfor %}
	</ul>
  
theme: jekyll-theme-minimal
